// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrGetArtist = `-- name: CreateOrGetArtist :one
INSERT INTO artists (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = artists.name
RETURNING id, name, created_at
`

func (q *Queries) CreateOrGetArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, createOrGetArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, created_at FROM artists
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getArtistsBySongID = `-- name: GetArtistsBySongID :many
SELECT a.id, a.name, a.created_at FROM artists a
INNER JOIN song_artists sa ON a.id = sa.artist_id
WHERE sa.song_id = $1
ORDER BY a.name
`

func (q *Queries) GetArtistsBySongID(ctx context.Context, songID int32) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtistsBySongID, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongWithArtists = `-- name: GetSongWithArtists :one
SELECT 
    s.id, s.title, s.album, s.duration_seconds, s.created_at,
    COALESCE(
        json_agg(
            json_build_object('id', a.id, 'name', a.name, 'created_at', a.created_at)
        ) FILTER (WHERE a.id IS NOT NULL),
        '[]'::json
    ) as artists
FROM songs s
LEFT JOIN song_artists sa ON s.id = sa.song_id
LEFT JOIN artists a ON sa.artist_id = a.id
WHERE s.id = $1
GROUP BY s.id
`

type GetSongWithArtistsRow struct {
	ID              int32            `json:"id"`
	Title           string           `json:"title"`
	Album           pgtype.Text      `json:"album"`
	DurationSeconds pgtype.Int4      `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	Artists         interface{}      `json:"artists"`
}

func (q *Queries) GetSongWithArtists(ctx context.Context, id int32) (GetSongWithArtistsRow, error) {
	row := q.db.QueryRow(ctx, getSongWithArtists, id)
	var i GetSongWithArtistsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Album,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.Artists,
	)
	return i, err
}

const getSongsWithArtists = `-- name: GetSongsWithArtists :many
SELECT 
    s.id, s.title, s.album, s.duration_seconds, s.created_at,
    COALESCE(
        json_agg(
            json_build_object('id', a.id, 'name', a.name, 'created_at', a.created_at)
        ) FILTER (WHERE a.id IS NOT NULL),
        '[]'::json
    ) as artists
FROM songs s
LEFT JOIN song_artists sa ON s.id = sa.song_id
LEFT JOIN artists a ON sa.artist_id = a.id
GROUP BY s.id
ORDER BY s.created_at DESC
`

type GetSongsWithArtistsRow struct {
	ID              int32            `json:"id"`
	Title           string           `json:"title"`
	Album           pgtype.Text      `json:"album"`
	DurationSeconds pgtype.Int4      `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	Artists         interface{}      `json:"artists"`
}

func (q *Queries) GetSongsWithArtists(ctx context.Context) ([]GetSongsWithArtistsRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSongsWithArtistsRow{}
	for rows.Next() {
		var i GetSongsWithArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Album,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSongToArtist = `-- name: LinkSongToArtist :exec
INSERT INTO song_artists (song_id, artist_id)
VALUES ($1, $2)
ON CONFLICT (song_id, artist_id) DO NOTHING
`

type LinkSongToArtistParams struct {
	SongID   int32 `json:"song_id"`
	ArtistID int32 `json:"artist_id"`
}

func (q *Queries) LinkSongToArtist(ctx context.Context, arg LinkSongToArtistParams) error {
	_, err := q.db.Exec(ctx, linkSongToArtist, arg.SongID, arg.ArtistID)
	return err
}
