// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fingerprints.sql

package db

import (
	"context"
)

const createFingerprint = `-- name: CreateFingerprint :one
INSERT INTO fingerprints (
    hash, song_id, time_offset
) VALUES (
    $1, $2, $3
)
RETURNING hash, song_id, time_offset
`

type CreateFingerprintParams struct {
	Hash       int64 `json:"hash"`
	SongID     int32 `json:"song_id"`
	TimeOffset int32 `json:"time_offset"`
}

func (q *Queries) CreateFingerprint(ctx context.Context, arg CreateFingerprintParams) (Fingerprint, error) {
	row := q.db.QueryRow(ctx, createFingerprint, arg.Hash, arg.SongID, arg.TimeOffset)
	var i Fingerprint
	err := row.Scan(&i.Hash, &i.SongID, &i.TimeOffset)
	return i, err
}

const deleteFingerprintsBySongID = `-- name: DeleteFingerprintsBySongID :exec
DELETE FROM fingerprints
WHERE song_id = $1
`

func (q *Queries) DeleteFingerprintsBySongID(ctx context.Context, songID int32) error {
	_, err := q.db.Exec(ctx, deleteFingerprintsBySongID, songID)
	return err
}

const getFingerprintsByHash = `-- name: GetFingerprintsByHash :many
SELECT hash, song_id, time_offset FROM fingerprints
WHERE hash = $1
`

func (q *Queries) GetFingerprintsByHash(ctx context.Context, hash int64) ([]Fingerprint, error) {
	rows, err := q.db.Query(ctx, getFingerprintsByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fingerprint{}
	for rows.Next() {
		var i Fingerprint
		if err := rows.Scan(&i.Hash, &i.SongID, &i.TimeOffset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFingerprintsByHashes = `-- name: GetFingerprintsByHashes :many
SELECT hash, song_id, time_offset FROM fingerprints
WHERE hash = ANY($1::bigint[])
`

func (q *Queries) GetFingerprintsByHashes(ctx context.Context, dollar_1 []int64) ([]Fingerprint, error) {
	rows, err := q.db.Query(ctx, getFingerprintsByHashes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fingerprint{}
	for rows.Next() {
		var i Fingerprint
		if err := rows.Scan(&i.Hash, &i.SongID, &i.TimeOffset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFingerprintsBySongID = `-- name: GetFingerprintsBySongID :many
SELECT hash, song_id, time_offset FROM fingerprints
WHERE song_id = $1
ORDER BY time_offset ASC
`

func (q *Queries) GetFingerprintsBySongID(ctx context.Context, songID int32) ([]Fingerprint, error) {
	rows, err := q.db.Query(ctx, getFingerprintsBySongID, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fingerprint{}
	for rows.Next() {
		var i Fingerprint
		if err := rows.Scan(&i.Hash, &i.SongID, &i.TimeOffset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
