// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fingerprint struct {
	Hash       int64 `json:"hash"`
	SongID     int32 `json:"song_id"`
	TimeOffset int32 `json:"time_offset"`
}

type Song struct {
	ID              int32            `json:"id"`
	Title           string           `json:"title"`
	Artist          string           `json:"artist"`
	Album           pgtype.Text      `json:"album"`
	DurationSeconds pgtype.Int4      `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}
