// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fingerprint struct {
	Hash         int64 `json:"hash"`
	SongID       int32 `json:"song_id"`
	TimeOffsetMs int32 `json:"time_offset_ms"`
}

type Song struct {
	ID         int32            `json:"id"`
	Title      string           `json:"title"`
	Artists    []byte           `json:"artists"`
	Album      pgtype.Text      `json:"album"`
	ImageUrl   pgtype.Text      `json:"image_url"`
	DurationMs pgtype.Int4      `json:"duration_ms"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
