// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateFingerprint(ctx context.Context, arg CreateFingerprintParams) (Fingerprint, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	DeleteFingerprintsBySongID(ctx context.Context, songID int32) error
	DeleteSong(ctx context.Context, id int32) error
	GetFingerprintsByHash(ctx context.Context, hash int64) ([]Fingerprint, error)
	GetFingerprintsByHashes(ctx context.Context, dollar_1 []int64) ([]Fingerprint, error)
	GetFingerprintsBySongID(ctx context.Context, songID int32) ([]Fingerprint, error)
	GetSong(ctx context.Context, id int32) (Song, error)
	GetSongByTitleAndArtist(ctx context.Context, arg GetSongByTitleAndArtistParams) (Song, error)
	ListSongs(ctx context.Context) ([]Song, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
}

var _ Querier = (*Queries)(nil)
