// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
    title, artists, album, duration_ms
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, title, artists, album, duration_ms, created_at
`

type CreateSongParams struct {
	Title      string      `json:"title"`
	Artists    []byte      `json:"artists"`
	Album      pgtype.Text `json:"album"`
	DurationMs pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.Title,
		arg.Artists,
		arg.Album,
		arg.DurationMs,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artists,
		&i.Album,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs
WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const getSong = `-- name: GetSong :one
SELECT id, title, artists, album, duration_ms, created_at FROM songs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSong(ctx context.Context, id int32) (Song, error) {
	row := q.db.QueryRow(ctx, getSong, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artists,
		&i.Album,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getSongByTitleAndArtists = `-- name: GetSongByTitleAndArtists :one
SELECT id, title, artists, album, duration_ms, created_at FROM songs
WHERE title = $1 AND artists = $2::jsonb
LIMIT 1
`

type GetSongByTitleAndArtistsParams struct {
	Title   string `json:"title"`
	Column2 []byte `json:"column_2"`
}

func (q *Queries) GetSongByTitleAndArtists(ctx context.Context, arg GetSongByTitleAndArtistsParams) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByTitleAndArtists, arg.Title, arg.Column2)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artists,
		&i.Album,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, title, artists, album, duration_ms, created_at FROM songs
ORDER BY created_at DESC
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artists,
			&i.Album,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET title = $2, artists = $3, album = $4, duration_ms = $5
WHERE id = $1
RETURNING id, title, artists, album, duration_ms, created_at
`

type UpdateSongParams struct {
	ID         int32       `json:"id"`
	Title      string      `json:"title"`
	Artists    []byte      `json:"artists"`
	Album      pgtype.Text `json:"album"`
	DurationMs pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, updateSong,
		arg.ID,
		arg.Title,
		arg.Artists,
		arg.Album,
		arg.DurationMs,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artists,
		&i.Album,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}
