// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
    title, artist, album, duration_seconds
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, title, artist, album, duration_seconds, created_at
`

type CreateSongParams struct {
	Title           string      `json:"title"`
	Artist          string      `json:"artist"`
	Album           pgtype.Text `json:"album"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationSeconds,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs
WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const getSong = `-- name: GetSong :one
SELECT id, title, artist, album, duration_seconds, created_at FROM songs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSong(ctx context.Context, id int32) (Song, error) {
	row := q.db.QueryRow(ctx, getSong, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const getSongByTitleAndArtist = `-- name: GetSongByTitleAndArtist :one
SELECT id, title, artist, album, duration_seconds, created_at FROM songs
WHERE title = $1 AND artist = $2
LIMIT 1
`

type GetSongByTitleAndArtistParams struct {
	Title  string `json:"title"`
	Artist string `json:"artist"`
}

func (q *Queries) GetSongByTitleAndArtist(ctx context.Context, arg GetSongByTitleAndArtistParams) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByTitleAndArtist, arg.Title, arg.Artist)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, title, artist, album, duration_seconds, created_at FROM songs
ORDER BY created_at DESC
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET title = $2, artist = $3, album = $4, duration_seconds = $5
WHERE id = $1
RETURNING id, title, artist, album, duration_seconds, created_at
`

type UpdateSongParams struct {
	ID              int32       `json:"id"`
	Title           string      `json:"title"`
	Artist          string      `json:"artist"`
	Album           pgtype.Text `json:"album"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, updateSong,
		arg.ID,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationSeconds,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}
