services:
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: shazam-build
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql

volumes:
  psql_volume:
